# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://katzir.xyz'
baseurl: 'katzir.xyz'
title: 'behind the keywords'
description: 'computers, books, culture'
permalink: pretty
logo: ""

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
# collections:
#  posts:
#    title: Blog
#    output: true
#    description: "There isn't much going on here yet, but watch this space"
